//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public string Doctor_Name { get; set; }
        public string Patient_Name { get; set; }
        public string Problem_list { get; set; }
        public string Prescription_File { get; set; }
        public string Prescription { get; set; }
        public string Payment_status { get; set; }
        public string Prescribed { get; set; }
    }
}
